apiVersion: v1
kind: Pod
metadata:
  name: simple-echo-2
spec:
  containers:
  - name: nginx
    image: gihyodocker/nginx:latest
    env:
    - name: BACKEND_HOST
      value: localhost:8080
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /data
        name: my-empty-volume
  - name: echo
    image: gihyodocker/echo:latest
    ports:
    - containerPort: 8080
    volumeMounts:
      - mountPath: /data
        name: my-empty-volume
  volumes:
    - name: my-empty-volume
      emptyDir: {}