# -*- mode: ruby -*- 
# vi: set ft=ruby :

Vagrant_API_Version="2"

Vagrant.configure(Vagrant_API_Version) do |config|
  # Node01
  config.vm.define:"k8s-node01" do |cfg|
    cfg.vm.box = "generic/centos7"
    cfg.vm.provider:virtualbox do |vb|
        vb.name="K8s-Node01"
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--memory", 1024]
    end
    cfg.vm.network "private_network", ip: "192.168.32.11"
    cfg.vm.network "forwarded_port", guest: 22, host: 19122, auto_correct: false, id: "ssh"
    cfg.vm.network "forwarded_port", guest: 80, host: 10080
    cfg.vm.provision "shell", path: "sshd_config.sh"
  end

  # Node02
  config.vm.define:"k8s-node02" do |cfg|
    cfg.vm.box = "generic/centos7"
    cfg.vm.provider:virtualbox do |vb|
        vb.name="K8s-Node02"
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--memory", 1024]
    end
    cfg.vm.network "private_network", ip: "192.168.32.12"
    cfg.vm.network "forwarded_port", guest: 22, host: 19222, auto_correct: false, id: "ssh"
    cfg.vm.network "forwarded_port", guest: 80, host: 20080
    cfg.vm.provision "shell", path: "sshd_config.sh"
  end

  # Master
  config.vm.define:"k8s-master" do |cfg|
    cfg.vm.box = "generic/centos7"
    cfg.vm.provider:virtualbox do |vb|
        vb.name="K8s-Master"
        vb.customize ["modifyvm", :id, "--cpus", 2]
        vb.customize ["modifyvm", :id, "--memory", 2048]
    end
    cfg.vm.synced_folder ".", "/vagrant"
    cfg.vm.network "private_network", ip: "192.168.32.10"
    cfg.vm.network "forwarded_port", guest: 22, host: 19022, auto_correct: false, id: "ssh"
    cfg.vm.provision "shell", path: "sshd_config.sh"
  end
end
